### ISSUE TITLE
NPE when getStops returns null

### ISSUE THREAD

**Issue by orlopau** [nadeldrucker/TrafficSwipe#52]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.nadeldrucker.trafficswipe, PID: 1898
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.stream.Stream java.util.List.stream()' on a null object reference
        at dev.nadeldrucker.trafficswipe.dao.transport.apis.vvo.VvoEntrypoint.lambda$getStops$1$VvoEntrypoint(VvoEntrypoint.java:31)
        at dev.nadeldrucker.trafficswipe.dao.transport.apis.vvo.-$$Lambda$VvoEntrypoint$F04ZokgkIs-_w3unfuEULmhGpX0.onResponse(Unknown Source:6)
        at dev.nadeldrucker.jvvo.Connection.lambda$post$0(Connection.java:61)
        at dev.nadeldrucker.jvvo.-$$Lambda$Connection$0HSXyuaOtddgkXsAhE8xSL3hCpY.onResponse(Unknown Source:8)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

Located at VvoEntrypoint:31 when creating stream and station is not present.
**Should return a DataWrapper with Error!**

**Comment by Philipp97714** [comment]
@orlopau I'm already working on this
