### ISSUE TITLE
App crashes when departures are null

### ISSUE THREAD

**Issue by orlopau** [nadeldrucker/TrafficSwipe#61]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.nadeldrucker.trafficswipe, PID: 26239
    java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.forEach(java.util.function.Consumer)' on a null object reference
        at dev.nadeldrucker.trafficswipe.data.publicTransport.apis.vvo.VvoStation.lambda$getDepartures$1$VvoStation(VvoStation.java:65)
        at dev.nadeldrucker.trafficswipe.data.publicTransport.apis.vvo.-$$Lambda$VvoStation$RmUTKM6IoUbL0AIu4gKsjD1ifDY.onResponse(Unknown Source:6)
        at dev.nadeldrucker.jvvo.Connection.lambda$post$0(Connection.java:61)
        at dev.nadeldrucker.jvvo.-$$Lambda$Connection$0HSXyuaOtddgkXsAhE8xSL3hCpY.onResponse(Unknown Source:8)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by orlopau** [comment]
prolly fixed
